---
virt: lxd
os: linux
arch: amd64
dist: focal
language: minimal

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python3-pip
  - sudo cat /proc/cpuinfo
  - sudo cat /proc/meminfo
  - free -m
  - mount
  - df -h .
  - find  /etc/apt/sources.list.d
  - cat /etc/apt/sources.list



install:
  - sudo -H python3 -m pip install --upgrade pip setuptools wheel
  - sudo -H python3 -m pip install --upgrade ansible
  - mkdir roles/
  - ansible-galaxy install -p roles -r requirements.yml

  # Add ansible.cfg to pick up roles path.
  - "printf '[defaults]\ngathering = smart\nroles_path = roles/' > ansible.cfg"

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook -vv -i tests/inventory tests/test.yml --syntax-check"
  # Run the role/playbook with ansible-playbook. -> en un LXD de Travis no se instala
  - "ansible-playbook -vv -i tests/inventory tests/test.yml --connection=local --tags devops --extra-vars @tests/hosts-vars.yml"
  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory tests/test.yml --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
# Request a page via the web server, to make sure it's running and responds.
#  - "curl http://localhost/"
