---
os: linux
arch: arm64
dist: bionic

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python3-pip
  - cat /proc/cpuinfo
  - cat /proc/meminfo
  - free -m
  - df -h 


install:
  - sudo -H python3 -m pip install --upgrade pip setuptools wheel
  - sudo -H python3 -m pip install --upgrade ansible
  - mkdir roles/
  - ansible-galaxy install -p roles -r requirements.yml

  # Add ansible.cfg to pick up roles path.
  - "printf '[defaults]\ngathering = smart\nroles_path = roles/' > ansible.cfg"

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
