---
- hosts: all

  tasks:

  - name: all | /etc/environment
    template:
      src: environment.j2
      dest: /etc/environment
      owner: root
      group: root
      mode: '0644'
    become: true
    tags: [ proxy ]

  - name: all | requisitos para modulo apt
    apt:
      name: aptitude
      state: present
    become: true

  - name: all | requisitos para modulo apt_repository
    apt:
      name: python3-apt
      state: present
    become: true

  - name: all | configura APT
    include_tasks: tasks/apt.yml
    tags: [ apt ]

  - name: all | instala y configura apt_fast
    include_tasks: tasks/instala_apt_fast.yml
    tags: [ apt-fast, apt ]

  - name: all | actualiza paquetes en sistema
    include_tasks: tasks/actualiza_sistema.yml
    tags: [ apt, upgrade ]

  - name: paquetes generales requisitos para instalar devops
    apt:
      name:
        - jq
        - git
        - wget
        - curl
        - socat
        - unzip
      state: present
    become: true

  - name: all | pup Parsing HTML at the command line
    include_tasks: tasks/instala_pup.yml
    tags: [ pup ]

  - name: all | mejora performance
    include_tasks: tasks/mejora_performance.yml
    tags: [ performance ]


  - name: all | configura locales
    include_role:
      name: locales
      apply:
        become: true
        tags:
          - all
          - locales
    tags:
      - all
      - locales
    vars:
      locales_present: 
        - es_AR.UTF-8
        - en_US.UTF-8
      locales_language_packs_present:
        - language-pack-en
        - language-pack-en-base
        - language-pack-es
        - language-pack-es-base
      locales_default:
        lang: es_AR.UTF-8
        #lc_all: C


