---
- hosts: escritorio

  tasks:

    # TODO:
    # template para /etc/systemd/timesyncd.conf poner los servidores NTP
    # sudo service systemd-timesyncd restart

  - include_tasks: tasks/instala_ffmpeg.yml
    tags: [ ffmpeg, video ]

  - include_tasks: tasks/paquetes_de_escritorio.yml
    tags: [ escritorio ]

  - include_tasks: tasks/sshfs-fuse.yml
    tags: [ escritorio ]

  - include_tasks: tasks/instala_snap.yml
    tags: 
      - escritorio
      - snap

  - include_tasks: tasks/dev_netbeans.yml
    tags: 
      - escritorio
      - netbeans

  - include_tasks: tasks/instala_codium.yml
    tags: 
      - escritorio
      - codium

  ## Microsoft VisualStudio Code es version privativa, uso VSCodium, el fork libre
  #- include_tasks: tasks/instala_microsoft_visualstudio_code.yml
  #  tags: 
  #    - escritorio
  #    - microsoft_visualstudio_code
  
  - include_tasks: tasks/instala_rambox.yml
    tags: [ rambox ]

  #- include_tasks: tasks/liveusb-multiboot.yml # no funciona correctamente sobre ubuntu 18.04 (2019/02/06)
  #tags: [ multiboot ]

  - include_tasks: tasks/unetbootin.yml
    tags: [ unetbootin ]

  #- include_tasks: tasks/instala_emulador_3270.yml # se usa para conectarse a minis y mainframes IBM

