---
- hosts: ocsinventoryagent
  become: true

  tasks:

    - name: ocsinventory-agent | incluye role
      include_role:
        name: ocsinventory-agent
        apply:
          tags: [ ocsinventory-agent ]
      when: ocs_server is defined and ocs_server|length 
      tags: [ always ]

    # https://fossies.org/linux/Ocsinventory-Unix-Agent/postinst.pl#l_345
    # instalador no es configurable con las opciones en el crontab
    # 28 11 * * * root /usr/local/bin/ocsinventory-agent --lazy > /dev/null 2>&1
    - name: ocsinventory-agent | asegura que no informa software
      lineinfile:
        path: /etc/cron.d/ocsinventory-agent
        regexp: '^(.*) /usr/local/bin/ocsinventory-agent --lazy (.*)$'
        line: '\1 /usr/local/bin/ocsinventory-agent --nosoftware --lazy \2'
        backrefs: yes
      when: ocs_server is defined and ocs_server|length 
      tags: [ ocsinventory-agent ]



# Para desinstalar deshacer lo que hizo:
# https://fossies.org/linux/Ocsinventory-Unix-Agent/postinst.pl
# En roles/ocsinventory-agent/defaults/main.yml estan los directorios defaults a eliminar
# Los paquetes APT que fueron dependencias: FIXME los dejo instalados

    - name: ocsinventory-agent | elimina el agente
      file:
        path: '{{ item }}'
        state: absent
      loop:
        - '/etc/cron.d/ocsinventory-agent'
        - '/usr/local/bin/ocsinventory-agent'
        # "{{ ocs_configdir }}"
        - '/etc/ocsinventory'
        # "{{ ocs_logfile }}"
        - '/var/log/ocsinventory-agent.log'
        # "{{ ocs_basedir }}"
        - '/var/lib/ocsinventory-agent'
      when: not ( ocs_server is defined and ocs_server|length )
      tags: [ ocsinventory-agent ]

