---

- name: actualiza | lista de paquetes .deb
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true
  tags:
    - apt
    - upgrade

- name: actualiza | apt-fast upgrade
  command: apt-fast -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
  become: true
  environment:
    DEBIAN_FRONTEND: "noninteractive"
    DEBCONF_NONINTERACTIVE_SEEN: "true"
    UCF_FORCE_CONFOLD: 1
  changed_when: false
  tags:
    - apt
    - upgrade

- name: actualiza | instala headers de Linux
  shell: |
    apt-fast install linux-headers-$( uname -r ) -y
    apt-fast install linux-headers-lowlatency -y

  become: true
  environment:
    DEBIAN_FRONTEND: "noninteractive"
    DEBCONF_NONINTERACTIVE_SEEN: "true"
    UCF_FORCE_CONFOLD: 1
  changed_when: false
  tags:
    - apt
    - upgrade

- name: actualiza | apt-fast dist-upgrade
  command: apt-fast -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade
  environment:
    DEBIAN_FRONTEND: "noninteractive"
    DEBCONF_NONINTERACTIVE_SEEN: "true"
    UCF_FORCE_CONFOLD: 1
  become: true
  changed_when: false
  tags:
    - apt
    - upgrade

- name: actualiza | apt-fast full-upgrade
  command: apt-fast -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" full-upgrade
  environment:
    DEBIAN_FRONTEND: "noninteractive"
    DEBCONF_NONINTERACTIVE_SEEN: "true"
    UCF_FORCE_CONFOLD: 1
  become: true
  changed_when: false
  tags:
    - apt
    - upgrade

- name: actualiza | apt-fast autoremove
  command: apt-fast -y autoremove
  become: true
  changed_when: false
  tags:
    - apt
    - upgrade

- name: actualiza | apt-fast clean
  command: apt-fast -y clean
  become: true
  changed_when: false
  tags:
    - apt
    - upgrade

