---
# See https://github.com/aelsabbahy/goss/releases for release versions

- name: devops | paquetes generales
  apt:
    name:
      - jq
      - git
      - wget
      - curl
      - unzip
    state: present
  become: true
  tags:
    - devops
    - aws


- name: devops | aws | version actual instalada
  shell: |
     LANG=C /usr/local/bin/aws --version | sed  -n "s@aws-cli/\([0-9\\.]*\) .*@\\1@p"

  register: reg_aws_version
  failed_when: false
  changed_when: false
  tags:
    - devops
    - aws


- name: devops | aws | busca el nombre de la version actual
  shell: |
      curl --silent  -H "Accept: application/vnd.github.v3+json"  https://api.github.com/repos/aws/aws-cli/tags | jq --raw-output ".[0].name"

  register: reg_aws_url_version
  changed_when: false
  ignore_errors: true
  args:
    warn: false
  tags:
    - devops
    - aws

- set_fact:
    aws_version_instalada: "{{ reg_aws_version.rc == 0 and reg_aws_version.stdout or false }}"
    aws_url_version: "{{ reg_aws_url_version.stdout if reg_aws_url_version.rc == 0 else '2.1.22' }}"
  tags:
    - devops
    - aws

- set_fact:
    aws_filename_actual: "awscli-exe-linux-x86_64-{{ aws_url_version }}.zip"
  tags:
    - devops
    - aws

- set_fact:
    aws_url_actual: "https://awscli.amazonaws.com/{{ aws_filename_actual }}"
  tags:
    - devops
    - aws

- debug:
    msg: "AWS, version instalada - {{ aws_version_instalada }}"
  tags:
    - devops
    - aws
- debug:
    msg: "AWS, url actual        - {{ aws_url_actual }}"
  tags:
    - devops
    - aws
- debug:
    msg: "AWS, url version       - {{ aws_url_version }}"
  tags:
    - devops
    - aws

- name: devops | aws | directorio de descarga
  file:
    path: /var/cache/aws-downloads
    state: directory
  become: true
  tags:
    - devops
    - aws

- name: devops | aws | descarga instalador
  get_url:
    url: "{{ aws_url_actual }}"
    dest: /var/cache/aws-downloads/
    mode: 0755
    force: yes
  become: true
  when: aws_version_instalada != aws_url_version
  tags:
    - devops
    - aws

- name: devops | aws | descomprime instalador
  unarchive:
    src: "/var/cache/aws-downloads/{{ aws_filename_actual }}"
    dest: /usr/local/
    remote_src: yes
  when: aws_version_instalada != aws_url_version
  become: true
  tags:
    - devops
    - aws

- name: devops | aws | corre instalador
  command: |
     ./install --update
  args:
    chdir: /usr/local/aws
  when: aws_version_instalada != aws_url_version
  become: true
  tags:
    - devops
    - aws

