---

- name: virtualbox | elimina versiones viejas de virtualbox
  apt:
    name:       
    - virtualbox-dkms
    - virtualbox-5.1
    - virtualbox-5.2
    state: absent
  become: true
  tags:
    - devops
    - virtualbox



- name: virtualbox | agrega clave del repo
  apt_key:
    url: 'https://www.virtualbox.org/download/oracle_vbox_2016.asc'
    state: present
  become: true
  tags:
    - devops
    - virtualbox

# TODO: no hay paquete al dia de hoy en focal: 2020-03-05
- set_fact:
        virtualbox_distro_release: "{{ ansible_distribution_release != 'focal' and ansible_distribution_release or 'eoan' }}"


- name: virtualbox | agrego repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ virtualbox_distro_release }} contrib"
    state: present
    update_cache: yes
    filename: virtualbox
  become: true
  register: reg_add_repo_vb
  tags:
    - devops
    - virtualbox


- name: virtualbox | actualizo lista paquetes .deb
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true
  when: reg_add_repo_vb is changed
  tags:
    - devops
    - virtualbox

- name: virtualbox | instala virtualbox
  apt:
    name: virtualbox-6.0
    state: present
  become: true
  tags:
    - devops
    - virtualbox



- name: virtualbox | VirtualBox version
  shell: "VBoxManage --version | awk -F'[r_]' '{print $1}'"
  register: reg_virtualbox_version
  changed_when: false
  tags:
    - devops
    - virtualbox

- name: virtualbox | Check if extension pack is already installed
  shell: "VBoxManage list extpacks"
  register: reg_extpack_list
  changed_when: false
  tags:
    - devops
    - virtualbox

- set_fact:
    ext_pack_claves: "{{ reg_extpack_list.stdout_lines | map('regex_replace', '^(?P<clave>.+):[ ]*(?P<valor>.+)$', '\\g<clave>') | list }}"
    ext_pack_valores: "{{ reg_extpack_list.stdout_lines | map('regex_replace', '^(?P<clave>.+):[ ]*(?P<valor>.+)$', '\\g<valor>') | list }}"
  tags:
    - devops
    - virtualbox

- set_fact:
    ext_pack_info: "{{ dict(ext_pack_claves | zip(ext_pack_valores)) }}"
  tags:
    - devops
    - virtualbox

- debug: var=ext_pack_info
  tags:
    - devops
    - virtualbox

- name: virtualbox | Output installed extpacks
  debug:
    msg: "{{ ext_pack_info['Version'] if ext_pack_info['Extension Packs'] != '0' else 'No hay extpacks instalados' }}"
  tags:
    - devops
    - virtualbox

# LatestVirtualBoxVersion=$(wget -qO - http://download.virtualbox.org/virtualbox/LATEST-STABLE.TXT) && wget "http://download.virtualbox.org/virtualbox/${LatestVirtualBoxVersion}/Oracle_VM_VirtualBox_Extension_Pack-${LatestVirtualBoxVersion}.vbox-extpack"
- name: virtualbox | Download VirtualBox extension pack
  get_url:
    url: "https://download.virtualbox.org/virtualbox/{{ reg_virtualbox_version.stdout }}/Oracle_VM_VirtualBox_Extension_Pack-{{ reg_virtualbox_version.stdout }}.vbox-extpack"
    dest: /tmp/
    force: yes
    #checksum: "sha256:https://www.virtualbox.org/download/hashes/{{ reg_virtualbox_version.stdout }}/SHA256SUMS"
  register: reg_download_result
  when: 'reg_extpack_list.stdout == "Extension Packs: 0" or ext_pack_info["Version"] != reg_virtualbox_version.stdout'
  tags:
    - devops
    - virtualbox

- name: virtualbox | Output downloaded VirtualBox extension pack file name
  debug:
    var: reg_download_result.dest
    verbosity: 1
  tags:
    - devops
    - virtualbox

- name: virtualbox | Install VirtualBox extension pack
  shell: "echo 'y' | VBoxManage extpack install --replace {{ reg_download_result.dest }}"
  when: 'reg_extpack_list.stdout == "Extension Packs: 0" or ext_pack_info["Version"] != reg_virtualbox_version.stdout'
  become: true
  tags:
    - devops
    - virtualbox

- name: virtualbox | make sure kernel modules are loaded
  modprobe:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - vboxnetadp
    - vboxnetflt
    - vboxdrv
  tags:
    - devops
    - virtualbox


