---

# config proxy https://elegantinfrastructure.com/docker/ultimate-guide-to-docker-http-proxy-configuration/

- name: devops | docker | install requisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    state: present
  become: true
  tags:
    - devops
    - docker

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html
# The apt-key command has been deprecated and suggests to ‘manage keyring files in trusted.gpg.d instead’.
# sudo apt-key list | less 
# 0EBF CD88 de docker
# sudo apt-key export 2980AECF | sudo gpg --dearmour -o /etc/apt/trusted.gpg.d/virtualbox.gpg
# sudo apt-key export 0EBFCD88 | sudo gpg --dearmour -o /etc/apt/trusted.gpg.d/docker.gpg

- name: devops | docker | agrega clave del repo
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    id: 8D81803C0EBFCD88
    state: present
  become: true
  tags:
    - devops
    - docker


- name: devops | docker | aseguro que /etc/default/docker no existe en systemd
  ansible.builtin.file:
    path: /etc/default/docker
    state: absent
  become: true
  when: ansible_service_mgr == 'systemd'
  tags:
    - devops
    - docker

# FIXME: sudo apt-key export 0EBFCD88 | sudo gpg --dearmour -o /usr/share/keyrings/docker.gpg


- name: devops | docker | agrego repo
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu  {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
    filename: docker
  become: true
  register: reg_add_repo_docker
  tags:
    - devops
    - docker


- name: devops | docker | actualizo lista paquetes .deb
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true
  when: reg_add_repo_docker is changed
  tags:
    - devops
    - docker

- name: devops | docker | instala docker-ce
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin # para compose v2, 18.04, 20.04, 22.04
      #- docker-compose         # para compose v1, 18.04, 20.04
    state: present
  become: true
  tags:
    - devops
    - docker


- name: devops | docker | Ensure 'docker' group exists
  group:
    name: docker
  become: yes
  tags:
    - devops
    - docker


- name: devops | docker | "Add users to 'docker' group."
  user:
    name:  "{{ devops_user_name }}"
    groups:
      - docker
    append: yes
  become: yes
  tags:
    - devops
    - docker


- name: devops | docker | Make sure that systemd directory exists
  file:
    path: '/etc/systemd/system'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: ansible_service_mgr == 'systemd'
  become: yes
  tags:
    - devops
    - docker

- name: devops | docker | Make sure that docker.service.d directory exists
  file:
    path: '/etc/systemd/system/docker.service.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: (ansible_service_mgr == 'systemd' and
        (docker__env_http_proxy is defined or docker__env_https_proxy is defined))
  become: yes
  tags:
    - devops
    - docker

- debug: var=docker__env_https_proxy
  tags:
    - devops
    - docker

- debug: var=https_proxy
  tags:
    - devops
    - docker

- name: devops | docker | configura proxy
  template:
    src: 'http-proxy.conf.j2'
    dest: '/etc/systemd/system/docker.service.d/http-proxy.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  become: yes
  register: reg_docker_proxy
  when: (ansible_service_mgr == 'systemd' and
        (docker__env_http_proxy is defined or docker__env_https_proxy is defined))
  vars :
    __env_http_proxy:  "{{ docker__env_http_proxy }}"
    __env_https_proxy: "{{ docker__env_https_proxy }}"
    __env_no_proxy:    "{{ docker__env_no_proxy}}"
  tags:
    - devops
    - docker

- name: devops | docker | docker deamon is running
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
  become: true
  when: reg_docker_proxy is changed
  tags:
    - devops
    - docker
