---

- name: paquetes generales requisitos para instalar devops
  apt:
    name: git
    state: present
  become: true
  tags:
    - devops
    - git

- name: devops | descarga completion de git para bash
  get_url:
    url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
    dest: ~/.git-prompt.sh
    mode: 0660
  become: true
  become_user: "{{ devops_user }}"
  tags:
    - devops
    - git

- name: devops | linea en .bashrc para completamientos git de bash
  lineinfile:
    path: ~/.bashrc
    line: 'source ~/.git-prompt.sh'
  become: true
  become_user: "{{ devops_user }}"
  tags:
    - devops
    - git



# FIXME: configurar ~/.gitconfig
