---
- set_fact:
    msteams_version_deseada: '1.3.00.5153'
  tags:
    - msteams


- name: msteams | agrega clave del repo
  apt_key:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    id: 'EB3E94ADBE1229CF'
    state: present
  become: true
  tags:
    - msteams


- name: msteams | agrego repo
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main"
    state: present
    update_cache: yes
    filename: teams
  become: true
  register: reg_add_repo_teams
  tags:
    - msteams


- name: msteams | agrego pin
  template:
    src: msteams-preference.j2
    dest: "/etc/apt/preferences.d/teams"
  become: true
  tags:
    - msteams


- name: msteams | actualizo lista paquetes .deb
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true
  when: reg_add_repo_teams is changed
  tags:
    - msteams


- name: msteams | instala msteams
  apt:
    name: teams={{ msteams_version_deseada }}
    state: present
    force: yes
  become: true
  tags:
    - msteams

