---

#  sudo add-apt-repository ppa:mc3man/trusty-media -y 
#  sudo apt-fast update
#  sudo apt-fast dist-upgrade -y
#
#  sudo apt-fast install ffmpeg -y
#  sudo apt-fast install x264 key-mon graphicsmagick -y


- name: ffmpeg | actualizo lista paquetes .deb
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true
  tags:
    - video
    - ffmpeg

- name: ffmpeg | instala ffmpeg
  apt:
    name:
      - ffmpeg
      - x264
      - graphicsmagick
    state: present
  become: true
  tags:
    - video
    - ffmpeg

# TODO: no hay paquete al dia de hoy en focal: 2020-03-05
- name: ffmpeg | instala key-mon excepto en focal
  apt:
    name:
      - key-mon
    state: present
  become: true
  when: ansible_distribution_release != "focal"
  tags:
    - video
    - ffmpeg

