---

- name: performance | actualizo lista paquetes .deb
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true
  tags: [ performance ]

- name: performance | instala preload, indicator-cpufreq, etc.
  apt:
    name: 
      - indicator-cpufreq
      #- laptop-mode-tools # es incompatible con tlp
      - preload
      - tlp
      - tlp-rdw
      - ubuntu-restricted-extras
    state: present
  become: true
  tags: [ performance ]


# TODO: para configurar laptop-mode-tools:
# sudo lmt-config-gui 

- name: performance | inicia tlp
  command: tlp start
  changed_when: false
  become: true
  tags: [ performance ]

##
# FIXME: desactiva animaciones - hacer que se guarde, sino anda en la sesión actual únicamente:
#
# gsettings set org.gnome.desktop.interface enable-animations 'false'
# gsettings set org.gnome.desktop.search-providers disable-external 'true'


- name: performance | ajusta swappiness
  sysctl:
    name: vm.swappiness
    value: "10"
    state: present
    reload: yes
  become: true
  tags: [ performance ]

- name: performance | ajusta vfs_cache_pressure
  sysctl:
    name: vm.vfs_cache_pressure
    value: "50"
    state: present
    reload: yes
  become: true
  tags: [ performance ]

