---

- name: performance | actualizo lista paquetes .deb
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true
  tags: [ performance ]

- name: performance | instala preload, indicator-cpufreq, etc.
  apt:
    name: 
      - indicator-cpufreq
      - preload
      - ubuntu-restricted-extras
    state: present
  become: true
  tags: [ performance ]

- name: performance | verificar si existe bateria
  shell: LANG=C upower -i /org/freedesktop/UPower/devices/battery_BATT | grep -E percentage | awk {'print $2'} | sed 's/[^0-9]*//g'
  register: exist_battery
  tags: [ performance ]

- name: performance | instala tlp
  apt:
    name: 
      #- laptop-mode-tools # es incompatible con tlp
      - tlp
      - tlp-rdw
    state: present
  become: true
  when: exist_battery.stdout|int > 0
  tags: [ performance ]

# TODO: para configurar laptop-mode-tools:
# sudo lmt-config-gui 

- name: performance | inicia tlp
  command: tlp start
  changed_when: false
  become: true
  when: exist_battery.stdout|int > 0
  tags: [ performance ]

##
# FIXME: desactiva animaciones - hacer que se guarde, sino anda en la sesión actual únicamente:
#
# gsettings set org.gnome.desktop.interface enable-animations 'false'
# gsettings set org.gnome.desktop.search-providers disable-external 'true'


- name: performance | ajusta swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ swappiness }}"
    state: present
    reload: yes
  become: true
  tags: [ performance ]

- name: performance | ajusta vfs_cache_pressure
  sysctl:
    name: vm.vfs_cache_pressure
    value: "50"
    state: present
    reload: yes
  become: true
  tags: [ performance ]

