---

- name: escritorio | agrego clave del repo de google chrome
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
  become: true
  tags:
    - escritorio

- name: escritorio | agrego repo google chrome
  apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    state: present
    filename: google-chrome
    update_cache: yes
  become: true
  tags:
    - escritorio

- name: escritorio | actualizo lista paquetes .deb
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true
  tags:
    - escritorio


- name: escritorio | libdvd-pkg config 1
  debconf:
    name: libdvd-pkg
    question: libdvd-pkg/build
    value: "True"
    vtype: boolean
  become: true
  changed_when: false
  tags:
    - escritorio

- name: escritorio | libdvd-pkg config 2
  debconf:
    name: libdvd-pkg
    question: libdvd-pkg/first-install
    value: ""
    vtype: note
  become: true
  tags:
    - escritorio

- name: escritorio | libdvd-pkg config 3
  debconf:
    name: libdvd-pkg
    question: libdvd-pkg/upgrade
    value: ""
    vtype: note
  become: true
  tags:
    - escritorio

- name: escritorio | libdvd-pkg config 4
  debconf:
    name: libdvd-pkg
    question: libdvd-pkg/post-invoke_hook-remove
    value: "False"
    vtype: boolean
  become: true
  changed_when: false
  tags:
    - escritorio

- name: escritorio | libdvd-pkg config 5
  debconf:
    name: libdvd-pkg
    question: libdvd-pkg/post-invoke_hook-install
    value: "True"
    vtype: boolean
  become: true
  changed_when: false
  tags:
    - escritorio

- name: escritorio | ttf-mscorefonts-installer
  debconf:
    name: ttf-mscorefonts-installer
    question: msttcorefonts/accepted-mscorefonts-eula
    value: "True"
    vtype: boolean
  become: true
  changed_when: false
  tags:
    - escritorio


- name: escritorio | completa instalacion de idiomas
  shell: apt install $(check-language-support)
  become: true
  tags:
    - escritorio


- name: escritorio | instala paquetes de servidor
  apt:
    name:
      - cgroup-tools
      - debconf-utils
      - deborphan
      - dnsmasq
      - inetutils-traceroute
      - iotop
      - iproute2
      - htop
      - mc
      - nocache
      - openssh-server
      - pv
      - rdiff-backup
      - screen
      - sshpass
    state: present
  become: true
  tags:
    - escritorio

- name: escritorio | instala varios
  apt:
    name:
      - antiword
      - axel
      - dia
      - djview4
      - elinks
      - eog
      - exfat-fuse
      - exfat-utils
      #- fdupes
      - google-chrome-stable
      - gpm
      - graphviz
      - ipcalc
      - libavcodec-extra
      - libnotify-bin
      #- libdvd-pkg
      - makepasswd
      - minicom
      - mplayer
      - nmap
      - recode
      - tree
      - ttf-mscorefonts-installer
      - vim
      - wv
      - x11-xkb-utils
      - xauth
      - xchm
      - xscreensaver
      - zram-config
      #- gnome-tweak-tool
    state: present
  become: true
  tags:
    - escritorio

- name: escritorio | elimina varios
  apt:
    name:
      - avahi-daemon
      - bamfdaemon
      - cups-browsed
      - deja-dup
      - empathy
      - evolution-data-server
      - gnome-software
      - indicator-messages
      - libzeitgeist-1.0-1
      - libzeitgeist-2.0-0
      - modemmanager
      - telepathy-indicator
    state: absent
  become: true
  tags:
    - escritorio

# http://duncanlock.net/blog/2013/05/03/how-to-set-your-compose-key-on-xfce-xubuntu-lxde-linux/
- name: escritorio | activa tecla de Compose
  shell: setxkbmap -option "compose:paus"
  failed_when: false
  tags:
    - escritorio

# http://rg3.github.io/youtube-dl/download.html
- name: escritorio | instala youtube-dl
  shell: |
      if [ ! -f /usr/local/bin/youtube-dl ] ; then
        curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
        chmod a+rx /usr/local/bin/youtube-dl
      fi

  changed_when: false
  become: true
  tags:
    - escritorio

- name: escritorio | actualiza youtube-dl
  command: python3 /usr/local/bin/youtube-dl --update
  changed_when: false
  become: true
  tags:
    - escritorio

- name: escritorio | configura cgroup-tools en grub
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="cgroup_enable=memory swapaccount=1"'
    owner: root
    group: root
    mode: 0644
    validate: 'sudo /usr/sbin/update-grub # %s'
  become: true
  tags:
    - escritorio


- name: escritorio | instala aplicaciones con flatpak
  import_tasks: tasks/instala_flatpak.yml
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "bionic"
  tags:
    - escritorio
    - flatpak


# FIXME:
#
#  sudo vi /usr/local/bin/gdmflexiserver
#
# #!/bin/sh
# # 
# # replacement for missing gdmflexiserver in Ubuntu 1[48].04
# #
# dm-tool switch-to-greeter
#
#  sudo chmod a+rx  /usr/local/bin/gdmflexiserver

